Добавлена работа с БД
leliaOff/java-filmorate pull request #8
Opened 2024-06-23 10:44 UTC by leliaOff

- реализация функционала со справочниками: получения списка жанров, списка рейтингов фильмов
- реализация функционала работы с пользователями: добавление, изменения, списки
- реалзиация функционала добавления пользовталей в друзья, подписки, отписки
- работа с фильмами: полчения списка фильмов, добавление, изменение
- голосования за фильмы: список проголосовавших пользователей, функционал голосования и отзыва голоса

2024-06-24 16:30 UTC, mikita95 requested changes
Все сделано просто отлично :) Оставил лишь небольшие замечания

2024-06-26 05:24 UTC, leliaOff commented on src/main/java/ru/yandex/practicum/filmorate/dal/repository/FilmUserRatingRepository.java
> +        update("INSERT INTO film_user_ratings(film_id, user_id) " +
Любопытно. Это позволило убрать лишнюю проверку, а, значит, и лишний запрос
Так же удалила лишнюю проверку и для запроса "отозвать голос"

2024-06-27 08:22 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-06-27 08:23 UTC, mikita95 requested changes
Все отлично :) Только не прошла сборка. Нужно, чтобы все прошло :)

2024-07-03 10:29 UTC, merged